### ISSUE TITLE
Incompatibility with current Piper release (after 25/02/2020)

### ISSUE THREAD

**Issue by kibi** [creactiviti/piper-pipelines#3]
Hi Arik,

It seems that the whole collections of pipelines is suffering from the same issue: lot's of pipelines use reserved word "output", 
for example, split_n_stitch.yaml, transcode.yaml, transcode_watermark.yaml, alteroutput.yaml and so on.

Could you please refresh the examples, so they correspond to the current revision of the Piper?

The coordinator service can't show the list of pipelines if one of them does not pass validations.

Best regards, 
Alexander Sorkin

**Comment by runabol** [comment]
This is fixed now. Thank you for your report!
